# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

title: 데이터시스템 구축 데이터
email: edangros@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  2021년 센서데이터 기반 빅데이터 시스템 전문가 양성사업 학습내용 정리
baseurl: "/SDDataExpertProgram2021" # the subpath of your site, e.g. /blog
url: "http://edangros.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: edangros
highlighter: rouge
svg:
  optimize: true
highlighter-theme: monokai
date_format: "%Y-%M-%D"

categories_path : categories.html
tags_path : tags.html
BASE_PATH : http://meliodus.github.io/uno-dbyll


# disqus_shortname: 'your-disqus-name'

author:
  name: edangros
  role: student
  email: edangros@gmail.com
  github: edangros